// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

/**
 * Drive to Gear uses vision output to keep the robot aimed such that the
 * gear goobler is centered focus of the two two by five vision targets on
 * the nearest lift on the alliance's air ship.  This should be the one that
 * was either the one intended by the operator or the goal of the last movement
 * sequence in Autonomous Mode. 
 */

package org.usfirst.frc4949.RobotSteamWorks.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4949.RobotSteamWorks.Robot;
import org.usfirst.frc4949.RobotSteamWorks.subsystems.Camera;

/**
 *
 */
public class DriveToGearLift extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveToGearLift() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.camera.initThreadToTargetLift();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double turn = Robot.camera.getTurn();
        double x = 0;
        double y = 0;
        double z = 0;
        double angle = 0;
        Robot.drive.mecanumDrive(x, y, z, angle);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.camera.killThreadToTargetLift();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
